## chart-releaser configuration
## https://github.com/helm/chart-releaser
owner: heliox-ai
git-base-url: https://api.github.com/
git-upload-url: https://uploads.github.com/
charts-repo-url: https://heliox-ai.github.io/heliox
