{{- if .Values.agent.enabled }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "heliox.fullname" . }}-agent
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "heliox.labels" . | nindent 4 }}
    app.kubernetes.io/component: agent
automountServiceAccountToken: false
{{- end }}
